[project]
name = "pydantic-ai-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "devtools>=0.12.2",
    "gradio>=5.23.1",
    "logfire>=3.11.0",
    "pydantic-ai>=0.0.46",
]
